name: Release

on:
  release:
    types: [published]

jobs:
  release:
    environment: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Obtain package and tag versions
        uses: geritol/match-tag-to-package-version@0.2.0
        id: versions

      - name: Check package and tag versions match
        if: steps.versions.outputs.PACKAGE_VERSION != steps.versions.outputs.TAG_VERSION
        run: exit 1

      - name: Using Node.js v14
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 14
          cache: 'yarn'
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: yarn --frozen-lockfile --no-progress

      - name: Set git author name
        run: git config --global user.name "Sergei Zharinov"
      - name: Set git author email
        run: git config --global user.email "sergio.zharinov@gmail.com"

      - name: Bump version
        run: npm version ${{ github.event.release.tag_name }}

      - name: Build
        run: yarn -s build

      - name: Test
        run: yarn -s test

      - name: Publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push bumped version
        run: git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
